version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build: .
    ports:
    # First port is inside of local machine, while second one is based inside of the container
      - "4001:8081"
